package ru.socit.pfr.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-04-22T23:54:00.607+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://service.pfr.socit.ru", name = "ServicePFR")
@XmlSeeAlso({org.w3._2004._08.xop.include.ObjectFactory.class, ru.gosuslugi.smev.rev111111.ObjectFactory.class, ru.socit.pfr.service.data.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicePFR {

    @WebResult(name = "ProcessResponse", targetNamespace = "http://service.pfr.socit.ru", partName = "parameters")
    @WebMethod(operationName = "Process")
    public ru.gosuslugi.smev.rev111111.BaseMessageType process(
        @WebParam(partName = "parameters", name = "Process", targetNamespace = "http://service.pfr.socit.ru")
        ru.gosuslugi.smev.rev111111.BaseMessageType parameters
    );
}
