package ru.socit.pfr.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-04-22T23:14:25.511+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "ServicePFRService", 
                  wsdlLocation = "file:/E:/smev-proxy/src/main/resources/wsdl/SID0003422.wsdl",
                  targetNamespace = "http://service.pfr.socit.ru") 
public class ServicePFRService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.pfr.socit.ru", "ServicePFRService");
    public final static QName ServicePFR = new QName("http://service.pfr.socit.ru", "ServicePFR");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/smev-proxy/src/main/resources/wsdl/SID0003422.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicePFRService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/smev-proxy/src/main/resources/wsdl/SID0003422.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicePFRService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicePFRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicePFRService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicePFRService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicePFRService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicePFRService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicePFR
     */
    @WebEndpoint(name = "ServicePFR")
    public ServicePFR getServicePFR() {
        return super.getPort(ServicePFR, ServicePFR.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePFR
     */
    @WebEndpoint(name = "ServicePFR")
    public ServicePFR getServicePFR(WebServiceFeature... features) {
        return super.getPort(ServicePFR, ServicePFR.class, features);
    }

}
