package ru.synq.smev.services.snils;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-05-08T11:53:41.656-04:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://snils-validation.skmv.rstyle.com", name = "SnilsValidationPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SnilsPort {

    @WebResult(name = "SnilsValidationResponse", targetNamespace = "http://snils-validation.skmv.rstyle.com", partName = "parameters")
    @WebMethod(operationName = "SnilsValidationRequest")
    public SnilsValidationResponseType snilsValidationRequest(
            @WebParam(partName = "parameters", name = "SnilsValidationRequest", targetNamespace = "http://snils-validation.skmv.rstyle.com")
            SnilsBaseMessage request
    );
}
