<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:impl="http://service.pfr.socit.ru" xmlns:intf="http://service.pfr.socit.ru" xmlns:smev="http://smev.gosuslugi.ru/rev111111" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://service.pfr.socit.ru">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://service.pfr.socit.ru">
         <import namespace="http://smev.gosuslugi.ru/rev111111" schemaLocation="http://smev-mvf.test.gosuslugi.ru:7777/gateway/services/SID0003422/1.00/wsdl/PFRF01/71e445be-19db-482e-b3ef-1f7db5914ef8" />
         <element name="Process" type="smev:BaseMessageType" />
         <element name="ProcessResponse" type="smev:BaseMessageType" />
      </schema>
   </wsdl:types>
   <wsdl:message name="ProcessRequest">
      <wsdl:part element="impl:Process" name="parameters" />
   </wsdl:message>
   <wsdl:message name="ProcessResponse">
      <wsdl:part element="impl:ProcessResponse" name="parameters" />
   </wsdl:message>
   <wsdl:portType name="ServicePFR">
      <wsdl:operation name="Process">
         <wsdl:input message="impl:ProcessRequest" name="ProcessRequest" />
         <wsdl:output message="impl:ProcessResponse" name="ProcessResponse" />
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="ServicePFRSoapBinding" type="impl:ServicePFR">
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
      <wsdl:operation name="Process">
         <wsdlsoap:operation soapAction="" />
         <wsdl:input name="ProcessRequest">
            <wsdlsoap:body use="literal" />
         </wsdl:input>
         <wsdl:output name="ProcessResponse">
            <wsdlsoap:body use="literal" />
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="ServicePFRService">
      <wsdl:port binding="impl:ServicePFRSoapBinding" name="ServicePFR">
         <wsdlsoap:address location="http://smev-mvf.test.gosuslugi.ru:7777/gateway/services/SID0003422/1.00" />
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>