package ru.fms.sx.kernel.webservices.incomingrequests.v2_4_3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-05-08T13:03:15.720-04:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru", name = "incomingRequestsService_v2_4_3")
@XmlSeeAlso({org.w3._2004._08.xop.include.ObjectFactory.class, ObjectFactory.class, ru.gosuslugi.smev.rev111111.ObjectFactory.class, ru.fms.sx.kernel.webservices.border.basetypes.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IncomingRequestsServiceV243 {

    @WebResult(name = "getResultResponse", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru", partName = "result")
    @WebMethod
    public ru.gosuslugi.smev.rev111111.GetResultResponseMessage getResult(
        @WebParam(partName = "parameters", name = "getResult", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru")
        ru.gosuslugi.smev.rev111111.GetResultMessage parameters
    );

    @WebResult(name = "processTaskResponse", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru", partName = "result")
    @WebMethod
    public ru.gosuslugi.smev.rev111111.ProcessTaskResponseMessage processTask(
        @WebParam(partName = "parameters", name = "processTask", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru")
        ru.gosuslugi.smev.rev111111.ServiceRequestMessage parameters
    );

    @WebResult(name = "getDictionaryValuesResponse", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru", partName = "result")
    @WebMethod
    public ru.gosuslugi.smev.rev111111.GetDictionaryValuesResponseMessage getDictionaryValues(
        @WebParam(partName = "parameters", name = "getDictionaryValues", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru")
        ru.gosuslugi.smev.rev111111.GetDictionaryValuesMessage parameters
    );

    @WebResult(name = "sendErrorReportResponse", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru", partName = "result")
    @WebMethod
    public ru.gosuslugi.smev.rev111111.SendErrorReportResponseMessage sendErrorReport(
        @WebParam(partName = "parameters", name = "sendErrorReport", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru")
        ru.gosuslugi.smev.rev111111.SendErrorReportMessage parameters
    );

    @WebResult(name = "getTaskTypesResponse", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru", partName = "result")
    @WebMethod
    public ru.gosuslugi.smev.rev111111.GetTaskTypesResponseMessage getTaskTypes(
        @WebParam(partName = "parameters", name = "getTaskTypes", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru")
        ru.gosuslugi.smev.rev111111.GetTaskTypesMessage parameters
    );

    @WebResult(name = "bookRequestResponse", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru", partName = "result")
    @WebMethod
    public ru.gosuslugi.smev.rev111111.BookRequestResponseMessage bookRequest(
        @WebParam(partName = "parameters", name = "bookRequest", targetNamespace = "http://v2_4_3.incomingRequests.webservices.kernel.sx.fms.ru")
        ru.gosuslugi.smev.rev111111.ServiceRequestMessage parameters
    );
}
