package unisoft.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-04-22T23:54:07.466+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://ws.unisoft/", name = "FNSINRWSPort")
@XmlSeeAlso({org.w3._2004._08.xop.include.ObjectFactory.class, ru.gosuslugi.smev.rev120315.ObjectFactory.class, unisoft.ws.sendsvfmsig.ObjectFactory.class, unisoft.ws.getsvfmsigresponse.ObjectFactory.class, unisoft.ws.getsvfmsig.ObjectFactory.class, ObjectFactory.class, unisoft.ws.sendsvfmsigresponse.ObjectFactory.class})
public interface FNSINRWSPort {

    @RequestWrapper(localName = "getSvFMSIG", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev120315.GetSvFMSIGRequestType")
    @WebMethod(action = "getSvFMSIG")
    @ResponseWrapper(localName = "getSvFMSIGResponse", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev120315.GetSvFMSIGResponseType")
    public void getSvFMSIG();

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TestResponse", targetNamespace = "http://ws.unisoft/", partName = "TestResponseParams")
    @WebMethod(operationName = "Test", action = "Test")
    public java.lang.String test(
        @WebParam(partName = "TestParams", name = "TestRequest", targetNamespace = "http://ws.unisoft/")
        java.lang.String testParams
    );

    @RequestWrapper(localName = "sendSvFMSIG", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev120315.SendSvFMSIGRequestType")
    @WebMethod(action = "sendSvFMSIG")
    @ResponseWrapper(localName = "sendSvFMSIGResponse", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev120315.SendSvFMSIGResponseType")
    public void sendSvFMSIG();
}
