package unisoft.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-05-06T17:14:43.828-04:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://ws.unisoft/", name = "FNSINNSvc_24Port")
@XmlSeeAlso({unisoft.ws.fnsinn.queryinnflgr.ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, ObjectFactory.class, ru.gosuslugi.smev.rev111111.ObjectFactory.class, unisoft.ws.fnsinn.response.ObjectFactory.class, unisoft.ws.fnsinn.queryinnfl.ObjectFactory.class, unisoft.ws.fnsinn.getinnflgr.ObjectFactory.class})
public interface FNSINNSvc24Port {

    @RequestWrapper(localName = "queryINNFL", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev111111.INNFL")
    @WebMethod(action = "queryINNFL")
    @ResponseWrapper(localName = "queryINNFLResponse", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev111111.INNFLRs")
    public void queryINNFL();

    @RequestWrapper(localName = "getINNFLGR", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev111111.ZPINNFLGR")
    @WebMethod(action = "getINNFLGR")
    @ResponseWrapper(localName = "getINNFLGRResponse", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev111111.OTINNFLGR")
    public void getINNFLGR();

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TestResponse", targetNamespace = "http://ws.unisoft/", partName = "TestRequest_OUT")
    @WebMethod(action = "test")
    public java.lang.String test(
        @WebParam(partName = "TestRequest_IN", name = "TestRequest", targetNamespace = "http://ws.unisoft/")
        java.lang.String testRequestIN
    );

    @RequestWrapper(localName = "queryINNFLGR", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev111111.INNFLGR")
    @WebMethod(action = "queryINNFLGR")
    @ResponseWrapper(localName = "queryINNFLGRResponse", targetNamespace = "http://ws.unisoft/", className = "ru.gosuslugi.smev.rev111111.INNFLGRRs")
    public void queryINNFLGR();
}
