package com.rstyle.skmv.snils_validation;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-05-08T13:03:18.099-04:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "SnilsValidationService", 
                  wsdlLocation = "wsdl/SNILS/snils.wsdl",
                  targetNamespace = "http://snils-validation.skmv.rstyle.com") 
public class SnilsValidationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://snils-validation.skmv.rstyle.com", "SnilsValidationService");
    public final static QName SnilsValidationPort = new QName("http://snils-validation.skmv.rstyle.com", "SnilsValidationPort");
    static {
        URL url = SnilsValidationService.class.getClassLoader().getResource("wsdl/SNILS/snils.wsdl");
        if (url == null) {
            throw new Error("Can not initialize the default wsdl from wsdl/SNILS/snils.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SnilsValidationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SnilsValidationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SnilsValidationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SnilsValidationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SnilsValidationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SnilsValidationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SnilsValidationPortType
     */
    @WebEndpoint(name = "SnilsValidationPort")
    public SnilsValidationPortType getSnilsValidationPort() {
        return super.getPort(SnilsValidationPort, SnilsValidationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SnilsValidationPortType
     */
    @WebEndpoint(name = "SnilsValidationPort")
    public SnilsValidationPortType getSnilsValidationPort(WebServiceFeature... features) {
        return super.getPort(SnilsValidationPort, SnilsValidationPortType.class, features);
    }

}
