package com.rstyle.skmv.snils_validation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-25T13:00:57.585+03:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://snils-validation.skmv.rstyle.com", name = "SnilsValidationPortType")
@XmlSeeAlso({org.w3._2004._08.xop.include.ObjectFactory.class, ObjectFactory.class, ru.gosuslugi.smev.rev120315.ObjectFactory.class, com.rstyle.skmv.pfr.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SnilsValidationPortType {

    @WebResult(name = "SnilsValidationResponse", targetNamespace = "http://snils-validation.skmv.rstyle.com", partName = "parameters")
    @WebMethod(operationName = "SnilsValidationRequest")
    public ru.gosuslugi.smev.rev120315.SnilsValidationResponseType snilsValidationRequest(
        @WebParam(partName = "SmevHeader", name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev120315", header = true)
        ru.gosuslugi.smev.rev120315.HeaderType smevHeader,
        @WebParam(partName = "parameters", name = "SnilsValidationRequest", targetNamespace = "http://snils-validation.skmv.rstyle.com")
        ru.gosuslugi.smev.rev120315.SnilsValidationRequestType parameters
    );
}
