package com.rstyle.skmv.snils_validation;

import ru.synq.smev.services.snils.SnilsBaseMessage;
import ru.synq.smev.services.snils.SnilsValidationResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-05-08T13:03:18.090-04:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://snils-validation.skmv.rstyle.com", name = "SnilsValidationPortType")
@XmlSeeAlso({ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, ru.gosuslugi.smev.rev120315.ObjectFactory.class, com.rstyle.skmv.pfr.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SnilsValidationPortType {

    @WebResult(name = "SnilsValidationResponse", targetNamespace = "http://snils-validation.skmv.rstyle.com", partName = "parameters")
    @WebMethod(operationName = "SnilsValidationRequest")
    public SnilsValidationResponse snilsValidationRequest(
        @WebParam(partName = "SmevHeader", name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev120315", header = true)
        ru.gosuslugi.smev.rev120315.HeaderType smevHeader,
        @WebParam(partName = "parameters", name = "SnilsValidationRequest", targetNamespace = "http://snils-validation.skmv.rstyle.com")
        SnilsBaseMessage parameters
    );
}
